drop extension if exists "pg_net";


  create table "public"."Game" (
    "game_id" bigint generated by default as identity not null,
    "league_id" bigint not null,
    "home_team" bigint not null,
    "away_team" bigint not null,
    "opening_possession" text,
    "home_attacks_right" boolean default true
      );



  create table "public"."League" (
    "league_id" bigint generated by default as identity not null,
    "name" text not null
      );



  create table "public"."Participants" (
    "play_id" bigint not null,
    "player_id" bigint not null,
    "role" text
      );



  create table "public"."Play" (
    "play_id" bigint generated by default as identity not null,
    "game_id" bigint not null,
    "offense_team" bigint not null,
    "defense_team" bigint not null,
    "first_half" boolean not null,
    "game_clock" text not null,
    "yard_line" bigint not null,
    "new_yard_line" bigint,
    "down" integer not null,
    "distance" bigint not null,
    "play_type" text not null,
    "outcome" text not null,
    "is_conversion" boolean not null,
    "conv_points" smallint,
    "home_good_play" boolean,
    "penalty_team_id" bigint
      );



  create table "public"."Player" (
    "player_id" bigint generated by default as identity not null,
    "team_id" bigint not null,
    "name" text not null
      );



  create table "public"."Roster" (
    "game_id" bigint not null,
    "player_id" bigint not null,
    "jersey" smallint
      );



  create table "public"."Team" (
    "team_id" bigint generated by default as identity not null,
    "league_id" bigint not null,
    "name" text not null
      );


CREATE UNIQUE INDEX "Game_pkey" ON public."Game" USING btree (game_id);

CREATE UNIQUE INDEX "League_pkey" ON public."League" USING btree (league_id);

CREATE UNIQUE INDEX "Participants_pkey" ON public."Participants" USING btree (play_id, player_id);

CREATE UNIQUE INDEX "Play_pkey" ON public."Play" USING btree (play_id);

CREATE UNIQUE INDEX "Player_pkey" ON public."Player" USING btree (player_id);

CREATE UNIQUE INDEX "Team_name_key" ON public."Team" USING btree (name);

CREATE UNIQUE INDEX "Team_pkey" ON public."Team" USING btree (team_id);

CREATE UNIQUE INDEX game_roster_pkey ON public."Roster" USING btree (game_id, player_id);

CREATE UNIQUE INDEX roster_game_player_unique ON public."Roster" USING btree (game_id, player_id);

alter table "public"."Game" add constraint "Game_pkey" PRIMARY KEY using index "Game_pkey";

alter table "public"."League" add constraint "League_pkey" PRIMARY KEY using index "League_pkey";

alter table "public"."Participants" add constraint "Participants_pkey" PRIMARY KEY using index "Participants_pkey";

alter table "public"."Play" add constraint "Play_pkey" PRIMARY KEY using index "Play_pkey";

alter table "public"."Player" add constraint "Player_pkey" PRIMARY KEY using index "Player_pkey";

alter table "public"."Roster" add constraint "game_roster_pkey" PRIMARY KEY using index "game_roster_pkey";

alter table "public"."Team" add constraint "Team_pkey" PRIMARY KEY using index "Team_pkey";

alter table "public"."Game" add constraint "Game_away_team_fkey" FOREIGN KEY (away_team) REFERENCES public."Team"(team_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Game" validate constraint "Game_away_team_fkey";

alter table "public"."Game" add constraint "Game_home_team_fkey" FOREIGN KEY (home_team) REFERENCES public."Team"(team_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Game" validate constraint "Game_home_team_fkey";

alter table "public"."Game" add constraint "Game_league_id_fkey" FOREIGN KEY (league_id) REFERENCES public."League"(league_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Game" validate constraint "Game_league_id_fkey";

alter table "public"."Participants" add constraint "Participants_play_id_fkey" FOREIGN KEY (play_id) REFERENCES public."Play"(play_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Participants" validate constraint "Participants_play_id_fkey";

alter table "public"."Participants" add constraint "Participants_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public."Player"(player_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Participants" validate constraint "Participants_player_id_fkey";

alter table "public"."Participants" add constraint "valid_role" CHECK ((role = ANY (ARRAY['passer'::text, 'rusher'::text, 'receiver'::text, 'defender'::text, 'interceptor'::text]))) not valid;

alter table "public"."Participants" validate constraint "valid_role";

alter table "public"."Play" add constraint "Play_defense_team_fkey" FOREIGN KEY (defense_team) REFERENCES public."Team"(team_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Play" validate constraint "Play_defense_team_fkey";

alter table "public"."Play" add constraint "Play_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public."Game"(game_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Play" validate constraint "Play_game_id_fkey";

alter table "public"."Play" add constraint "Play_offense_team_fkey" FOREIGN KEY (offense_team) REFERENCES public."Team"(team_id) not valid;

alter table "public"."Play" validate constraint "Play_offense_team_fkey";

alter table "public"."Play" add constraint "Play_penalty_team_id_fkey" FOREIGN KEY (penalty_team_id) REFERENCES public."Team"(team_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Play" validate constraint "Play_penalty_team_id_fkey";

alter table "public"."Player" add constraint "Player_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public."Team"(team_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Player" validate constraint "Player_team_id_fkey";

alter table "public"."Roster" add constraint "game_roster_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public."Game"(game_id) ON DELETE CASCADE not valid;

alter table "public"."Roster" validate constraint "game_roster_game_id_fkey";

alter table "public"."Roster" add constraint "game_roster_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public."Player"(player_id) not valid;

alter table "public"."Roster" validate constraint "game_roster_player_id_fkey";

alter table "public"."Roster" add constraint "roster_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public."Game"(game_id) ON DELETE CASCADE not valid;

alter table "public"."Roster" validate constraint "roster_game_id_fkey";

alter table "public"."Roster" add constraint "roster_game_player_unique" UNIQUE using index "roster_game_player_unique";

alter table "public"."Team" add constraint "Team_league_id_fkey" FOREIGN KEY (league_id) REFERENCES public."League"(league_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Team" validate constraint "Team_league_id_fkey";

alter table "public"."Team" add constraint "Team_name_key" UNIQUE using index "Team_name_key";

grant delete on table "public"."Game" to "anon";

grant insert on table "public"."Game" to "anon";

grant references on table "public"."Game" to "anon";

grant select on table "public"."Game" to "anon";

grant trigger on table "public"."Game" to "anon";

grant truncate on table "public"."Game" to "anon";

grant update on table "public"."Game" to "anon";

grant delete on table "public"."Game" to "authenticated";

grant insert on table "public"."Game" to "authenticated";

grant references on table "public"."Game" to "authenticated";

grant select on table "public"."Game" to "authenticated";

grant trigger on table "public"."Game" to "authenticated";

grant truncate on table "public"."Game" to "authenticated";

grant update on table "public"."Game" to "authenticated";

grant delete on table "public"."Game" to "service_role";

grant insert on table "public"."Game" to "service_role";

grant references on table "public"."Game" to "service_role";

grant select on table "public"."Game" to "service_role";

grant trigger on table "public"."Game" to "service_role";

grant truncate on table "public"."Game" to "service_role";

grant update on table "public"."Game" to "service_role";

grant delete on table "public"."League" to "anon";

grant insert on table "public"."League" to "anon";

grant references on table "public"."League" to "anon";

grant select on table "public"."League" to "anon";

grant trigger on table "public"."League" to "anon";

grant truncate on table "public"."League" to "anon";

grant update on table "public"."League" to "anon";

grant delete on table "public"."League" to "authenticated";

grant insert on table "public"."League" to "authenticated";

grant references on table "public"."League" to "authenticated";

grant select on table "public"."League" to "authenticated";

grant trigger on table "public"."League" to "authenticated";

grant truncate on table "public"."League" to "authenticated";

grant update on table "public"."League" to "authenticated";

grant delete on table "public"."League" to "service_role";

grant insert on table "public"."League" to "service_role";

grant references on table "public"."League" to "service_role";

grant select on table "public"."League" to "service_role";

grant trigger on table "public"."League" to "service_role";

grant truncate on table "public"."League" to "service_role";

grant update on table "public"."League" to "service_role";

grant delete on table "public"."Participants" to "anon";

grant insert on table "public"."Participants" to "anon";

grant references on table "public"."Participants" to "anon";

grant select on table "public"."Participants" to "anon";

grant trigger on table "public"."Participants" to "anon";

grant truncate on table "public"."Participants" to "anon";

grant update on table "public"."Participants" to "anon";

grant delete on table "public"."Participants" to "authenticated";

grant insert on table "public"."Participants" to "authenticated";

grant references on table "public"."Participants" to "authenticated";

grant select on table "public"."Participants" to "authenticated";

grant trigger on table "public"."Participants" to "authenticated";

grant truncate on table "public"."Participants" to "authenticated";

grant update on table "public"."Participants" to "authenticated";

grant delete on table "public"."Participants" to "service_role";

grant insert on table "public"."Participants" to "service_role";

grant references on table "public"."Participants" to "service_role";

grant select on table "public"."Participants" to "service_role";

grant trigger on table "public"."Participants" to "service_role";

grant truncate on table "public"."Participants" to "service_role";

grant update on table "public"."Participants" to "service_role";

grant delete on table "public"."Play" to "anon";

grant insert on table "public"."Play" to "anon";

grant references on table "public"."Play" to "anon";

grant select on table "public"."Play" to "anon";

grant trigger on table "public"."Play" to "anon";

grant truncate on table "public"."Play" to "anon";

grant update on table "public"."Play" to "anon";

grant delete on table "public"."Play" to "authenticated";

grant insert on table "public"."Play" to "authenticated";

grant references on table "public"."Play" to "authenticated";

grant select on table "public"."Play" to "authenticated";

grant trigger on table "public"."Play" to "authenticated";

grant truncate on table "public"."Play" to "authenticated";

grant update on table "public"."Play" to "authenticated";

grant delete on table "public"."Play" to "service_role";

grant insert on table "public"."Play" to "service_role";

grant references on table "public"."Play" to "service_role";

grant select on table "public"."Play" to "service_role";

grant trigger on table "public"."Play" to "service_role";

grant truncate on table "public"."Play" to "service_role";

grant update on table "public"."Play" to "service_role";

grant delete on table "public"."Player" to "anon";

grant insert on table "public"."Player" to "anon";

grant references on table "public"."Player" to "anon";

grant select on table "public"."Player" to "anon";

grant trigger on table "public"."Player" to "anon";

grant truncate on table "public"."Player" to "anon";

grant update on table "public"."Player" to "anon";

grant delete on table "public"."Player" to "authenticated";

grant insert on table "public"."Player" to "authenticated";

grant references on table "public"."Player" to "authenticated";

grant select on table "public"."Player" to "authenticated";

grant trigger on table "public"."Player" to "authenticated";

grant truncate on table "public"."Player" to "authenticated";

grant update on table "public"."Player" to "authenticated";

grant delete on table "public"."Player" to "service_role";

grant insert on table "public"."Player" to "service_role";

grant references on table "public"."Player" to "service_role";

grant select on table "public"."Player" to "service_role";

grant trigger on table "public"."Player" to "service_role";

grant truncate on table "public"."Player" to "service_role";

grant update on table "public"."Player" to "service_role";

grant delete on table "public"."Roster" to "anon";

grant insert on table "public"."Roster" to "anon";

grant references on table "public"."Roster" to "anon";

grant select on table "public"."Roster" to "anon";

grant trigger on table "public"."Roster" to "anon";

grant truncate on table "public"."Roster" to "anon";

grant update on table "public"."Roster" to "anon";

grant delete on table "public"."Roster" to "authenticated";

grant insert on table "public"."Roster" to "authenticated";

grant references on table "public"."Roster" to "authenticated";

grant select on table "public"."Roster" to "authenticated";

grant trigger on table "public"."Roster" to "authenticated";

grant truncate on table "public"."Roster" to "authenticated";

grant update on table "public"."Roster" to "authenticated";

grant delete on table "public"."Roster" to "service_role";

grant insert on table "public"."Roster" to "service_role";

grant references on table "public"."Roster" to "service_role";

grant select on table "public"."Roster" to "service_role";

grant trigger on table "public"."Roster" to "service_role";

grant truncate on table "public"."Roster" to "service_role";

grant update on table "public"."Roster" to "service_role";

grant delete on table "public"."Team" to "anon";

grant insert on table "public"."Team" to "anon";

grant references on table "public"."Team" to "anon";

grant select on table "public"."Team" to "anon";

grant trigger on table "public"."Team" to "anon";

grant truncate on table "public"."Team" to "anon";

grant update on table "public"."Team" to "anon";

grant delete on table "public"."Team" to "authenticated";

grant insert on table "public"."Team" to "authenticated";

grant references on table "public"."Team" to "authenticated";

grant select on table "public"."Team" to "authenticated";

grant trigger on table "public"."Team" to "authenticated";

grant truncate on table "public"."Team" to "authenticated";

grant update on table "public"."Team" to "authenticated";

grant delete on table "public"."Team" to "service_role";

grant insert on table "public"."Team" to "service_role";

grant references on table "public"."Team" to "service_role";

grant select on table "public"."Team" to "service_role";

grant trigger on table "public"."Team" to "service_role";

grant truncate on table "public"."Team" to "service_role";

grant update on table "public"."Team" to "service_role";


